name: "Create Releases"
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Build for ARM64 and AMD64 on Linux (Debian/Ubuntu compatible)
        goos: [linux]
        goarch: [amd64, arm64]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.4'
    
    - name: Build binary
      run: |
        GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o gigafind-${{ matrix.goos }}-${{ matrix.goarch }} .
    
    - name: Create archive
      run: |
        tar -czf gigafind-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz gigafind-${{ matrix.goos }}-${{ matrix.goarch }} README.md CLAUDE.md
    
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: gigafind-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
